import { supabase } from "@/integrations/supabase/client";

export type Level = "N5" | "N4" | "N3" | "N2" | "N1";
export const LEVELS: Level[] = ["N5", "N4", "N3", "N2", "N1"];
export type Example = { jp?: string; id?: string; reading?: string };
export type RelatedWord = { term: string; reading?: string | null; meaning?: string | null };
export function asExamples(value: unknown): Example[] {
  if (!value) return [];
  const raw = Array.isArray(value) ? value : typeof value === "string" ? (() => { try { return JSON.parse(value); } catch { return [value]; } })() : [];
  if (!Array.isArray(raw)) return [];
  return raw.map((item) => {
    if (typeof item === "string") return { jp: item };
    if (!item || typeof item !== "object") return {};
    const x = item as Record<string, unknown>;
    return { jp: String(x.jp ?? x.japanese ?? x.sentence ?? x.example ?? "") || undefined, id: String(x.id ?? x.indonesian ?? x.translation ?? x.translation_id ?? "") || undefined, reading: String(x.reading ?? x.hiragana ?? "") || undefined };
  }).filter((x) => x.jp || x.id);
}
function must<T>(res: { data: T | null; error: { message: string } | null }): T { if (res.error) throw new Error(res.error.message); return (res.data ?? []) as T; }
function dayNumber() { return Math.floor(Date.now() / 86400000); }
function windowStart(count: number, step: number) { return count > 0 ? (dayNumber() * step) % count : 0; }

const fallbackPassage = { id: "fallback-dokkai-n5-1", title: "毎朝の習慣", level: "N5" as Level, body_jp: "私は毎朝七時に起きます。顔を洗って、朝ご飯を食べます。\n\n八時に家を出て、駅まで歩きます。駅は家から十分ぐらいです。", body_furigana: "[私|わたし]は[毎朝|まいあさ][七時|しちじ]に[起|お]きます。[顔|かお]を[洗|あら]って、[朝|あさ]ご[飯|はん]を[食|た]べます。\n\n[八時|はちじ]に[家|いえ]を[出|で]て、[駅|えき]まで[歩|ある]きます。[駅|えき]は[家|いえ]から[十分|じゅっぷん]ぐらいです。", translation_id: "Saya bangun setiap pagi pukul tujuh. Saya mencuci muka lalu sarapan.\n\nPukul delapan saya keluar rumah dan berjalan sampai stasiun. Stasiun sekitar sepuluh menit dari rumah.", estimated_minutes: 3, sort_order: 1, is_published: true };
const fallbackPassageQuestions = [
  { id: "fallback-dokkai-q1", prompt: "何時に起きますか。", prompt_note: null, choices: ["六時", "七時", "八時", "九時"], correct_index: 1, explanation_id: "Teks menyebutkan bahwa penulis bangun pukul tujuh." },
  { id: "fallback-dokkai-q2", prompt: "駅まで何分ぐらいですか。", prompt_note: null, choices: ["五分", "十分", "十五分", "二十分"], correct_index: 1, explanation_id: "Stasiun berjarak sekitar sepuluh menit dari rumah." },
];
const fallbackListening = { id: "fallback-choukai-n5-1", title: "朝の予定", level: "N5" as Level, duration_seconds: 1, audio_url: null, source: "ENO JAPAN", transcript_jp: "明日は朝七時に起きます。八時に学校へ行きます。", translation_id: "Besok saya bangun pukul tujuh pagi. Pukul delapan saya pergi ke sekolah.", sort_order: 1, is_published: true };
const fallbackListeningQuestions = [{ id: "fallback-choukai-q1", prompt: "明日は何時に学校へ行きますか。", choices: ["七時", "八時", "九時", "十時"], correct_index: 1, explanation_id: "Audio menyebutkan bahwa pergi ke sekolah pukul delapan." }];
const fallbackQuizQuestions = [
  { id: "fallback-quiz-q1", prompt: "これは（　）です。", prompt_note: "毎日使うものです。", choices: ["ほん", "みず", "たべる", "おきる"], correct_index: 0, explanation_id: "「ほん」は buku." },
  { id: "fallback-quiz-q2", prompt: "私は毎朝七時（　）起きます。", prompt_note: null, choices: ["を", "に", "で", "が"], correct_index: 1, explanation_id: "Waktu menggunakan partikel に." },
  { id: "fallback-quiz-q3", prompt: "「大きい」の反対は何ですか。", prompt_note: null, choices: ["小さい", "新しい", "古い", "高い"], correct_index: 0, explanation_id: "大きい berarti besar; lawannya 小さい berarti kecil." },
  { id: "fallback-quiz-q4", prompt: "昨日、学校（　）行きました。", prompt_note: null, choices: ["へ", "を", "が", "と"], correct_index: 0, explanation_id: "へ menunjukkan arah/tujuan." },
  { id: "fallback-quiz-q5", prompt: "「食べます」の意味は何ですか。", prompt_note: null, choices: ["minum", "makan", "tidur", "pergi"], correct_index: 1, explanation_id: "食べます berarti makan." },
];

export async function fetchKanjiList(level: Level) {
  const countRes = await supabase.from("kanji").select("id", { count: "exact", head: true }).eq("level", level).eq("is_published", true);
  if (countRes.error) throw new Error(countRes.error.message);
  const count = countRes.count ?? 0;
  if (!count) return [];
  return must(await supabase.from("kanji").select("id, character, level, onyomi, kunyomi, meaning_id, stroke_count, sort_order").eq("level", level).eq("is_published", true).order("sort_order").range(windowStart(count, 17), windowStart(count, 17) + 59));
}
export async function fetchKanjiDetail(id: string) { const kanji = must(await supabase.from("kanji").select("*").eq("id", id).eq("is_published", true).limit(1)); const relations = must(await supabase.from("kanji_relations").select("id, note_id, sort_order, related:related_kanji_id (id, character, meaning_id, level)").eq("kanji_id", id).order("sort_order")); return { kanji: kanji[0] ?? null, relations }; }
export async function fetchKanjiStudy(id: string) { const kanjiRows = must(await supabase.from("kanji").select("*").eq("id", id).eq("is_published", true).limit(1)); const kanji = kanjiRows[0] ?? null; if (!kanji) return { kanji: null, examples: [] as Example[], relatedWords: [] as RelatedWord[] }; const char = String(kanji.character ?? ""); const vocabRows = must(await supabase.from("vocabulary").select("term, reading, meaning_id, examples").eq("is_published", true).ilike("term", `%${char}%`).limit(8)); const relatedWords: RelatedWord[] = []; const examples: Example[] = []; for (const v of vocabRows as Array<Record<string, unknown>>) { relatedWords.push({ term: String(v["term"] ?? ""), reading: v["reading"] ? String(v["reading"]) : null, meaning: v["meaning_id"] ? String(v["meaning_id"]) : null }); const ve = asExamples(v["examples"]); if (ve.length) examples.push(...ve); } return { kanji, examples: examples.slice(0, 5), relatedWords: relatedWords.filter(v => v.term) }; }
export async function fetchVocabList(level: Level) { const countRes = await supabase.from("vocabulary").select("id", { count: "exact", head: true }).eq("level", level).eq("is_published", true); if (countRes.error) throw new Error(countRes.error.message); const count = countRes.count ?? 0; if (!count) return []; return must(await supabase.from("vocabulary").select("id, term, reading, romaji, meaning_id, meaning_en, part_of_speech, examples, level, sort_order").eq("level", level).eq("is_published", true).order("sort_order").range(windowStart(count, 31), windowStart(count, 31) + 59)); }
export async function fetchGrammarList(level: Level) { const countRes = await supabase.from("grammar_points").select("id", { count: "exact", head: true }).eq("level", level).eq("is_published", true); if (countRes.error) throw new Error(countRes.error.message); const count = countRes.count ?? 0; if (!count) return []; return must(await supabase.from("grammar_points").select("id, pattern, meaning_id, meaning_en, structure, explanation_id, examples, level, sort_order").eq("level", level).eq("is_published", true).order("sort_order").range(windowStart(count, 13), windowStart(count, 13) + 39)); }

export async function fetchPassages() { const rows = await supabase.from("reading_passages").select("id, title, level, body_jp, translation_id, estimated_minutes, sort_order").eq("is_published", true).order("sort_order"); if (!rows.error && rows.data?.length) return rows.data; return [fallbackPassage]; }
export async function fetchPassageDetail(id: string) { if (id === fallbackPassage.id) return { passage: fallbackPassage, questions: fallbackPassageQuestions }; const passages = must(await supabase.from("reading_passages").select("*").eq("id", id).limit(1)); const questions = must(await supabase.from("questions").select("id, prompt, prompt_note, choices, correct_index, explanation_id").eq("passage_id", id).eq("is_published", true)); return { passage: passages[0] ?? null, questions }; }
export async function fetchListeningList() { const rows = await supabase.from("listening_items").select("id, title, level, duration_seconds, sort_order, audio_url, source").eq("is_published", true).order("sort_order"); if (!rows.error && rows.data?.length) return rows.data; return [fallbackListening]; }
export async function fetchListeningDetail(id: string) { if (id === fallbackListening.id) return { item: fallbackListening, questions: fallbackListeningQuestions }; const items = must(await supabase.from("listening_items").select("*").eq("id", id).limit(1)); const questions = must(await supabase.from("questions").select("id, prompt, choices, correct_index, explanation_id").eq("listening_id", id).eq("is_published", true)); return { item: items[0] ?? null, questions }; }

export async function fetchQuizzes() { const rows = await supabase.from("quizzes").select("id, slug, title, description, level, skill, question_count, time_limit_seconds, sort_order").eq("is_published", true).order("level").order("sort_order"); if (!rows.error && rows.data?.length) return rows.data; return LEVELS.map(level => ({ id: `fallback-${level}`, slug: `simulasi-jlpt-${level}`, title: `Simulasi JLPT ${level}`, description: `Simulasi latihan ${level}`, level, skill: null, question_count: fallbackQuizQuestions.length, time_limit_seconds: 600, sort_order: 0 })); }
export type RunnerQuestion = { id: string; prompt: string; prompt_note: string | null; choices: string[]; correct_index: number; explanation_id: string | null; };
function toRunnerQuestions(rows: unknown[]): RunnerQuestion[] { return (rows as Array<Record<string, unknown>>).map(q => ({ id: String(q["id"]), prompt: String(q["prompt"]), prompt_note: (q["prompt_note"] as string | null) ?? null, choices: Array.isArray(q["choices"]) ? (q["choices"] as string[]).map(String) : [], correct_index: Number(q["correct_index"]), explanation_id: (q["explanation_id"] as string | null) ?? null })); }
export async function fetchQuizBySlug(slug: string) { if (slug.startsWith("simulasi-jlpt-")) { const level = slug.replace("simulasi-jlpt-", "") as Level; const valid = LEVELS.includes(level); if (valid) { const quizzes = await supabase.from("quizzes").select("*").eq("slug", slug).eq("is_published", true).limit(1); if (!quizzes.error && quizzes.data?.[0]) { const quiz = quizzes.data[0]; const rows = must(await supabase.from("quiz_questions").select("sort_order, question:question_id (id, prompt, prompt_note, choices, correct_index, explanation_id, is_published)").eq("quiz_id", quiz.id).order("sort_order")) as Array<{ question: Record<string, unknown> | null }>; return { quiz, questions: toRunnerQuestions(rows.map(r => r.question).filter((q): q is Record<string, unknown> => !!q && q["is_published"] === true)) }; } return { quiz: { id: `fallback-${level}`, slug, title: `Simulasi JLPT ${level}`, description: `Simulasi latihan ${level}`, level, skill: null, question_count: fallbackQuizQuestions.length, time_limit_seconds: 600, sort_order: 0 }, questions: toRunnerQuestions(fallbackQuizQuestions) }; } } const quizzes = must(await supabase.from("quizzes").select("*").eq("slug", slug).eq("is_published", true).limit(1)); const quiz = quizzes[0] ?? null; if (!quiz) return { quiz: null, questions: [] as RunnerQuestion[] }; const rows = must(await supabase.from("quiz_questions").select("sort_order, question:question_id (id, prompt, prompt_note, choices, correct_index, explanation_id, is_published)").eq("quiz_id", quiz.id).order("sort_order")) as Array<{ question: Record<string, unknown> | null }>; return { quiz, questions: toRunnerQuestions(rows.map(r => r.question).filter((q): q is Record<string, unknown> => !!q && q["is_published"] === true)) }; }
export type SimSkillGroup = "vocabulary_grammar" | "reading" | "listening";
export async function fetchSimulationQuestions(level: Level, group: SimSkillGroup) { const skills = group === "vocabulary_grammar" ? (["vocabulary", "grammar", "kanji"] as const) : group === "reading" ? (["reading"] as const) : (["listening"] as const); const rows = must(await supabase.from("questions").select("id, prompt, prompt_note, choices, correct_index, explanation_id, level, skill").eq("is_published", true).eq("level", level).in("skill", skills as unknown as ("kanji"|"vocabulary"|"grammar"|"reading"|"listening")[]).limit(12)); return rows.length ? toRunnerQuestions(rows as unknown[]) : toRunnerQuestions(fallbackQuizQuestions); }
export async function saveAttempt(input: { quizId?: string | null; level?: Level | null; skill?: "kanji" | "vocabulary" | "grammar" | "reading" | "listening" | null; total: number; correct: number; durationSeconds: number; answers: Array<{ questionId: string; selectedIndex: number; isCorrect: boolean }> }) { const { data: userRes } = await supabase.auth.getUser(); const userId = userRes.user?.id; if (!userId) return; const score = input.total > 0 ? Math.round((input.correct / input.total) * 10000) / 100 : 0; const xpEarned = input.correct * 10; const { data: attempt, error } = await supabase.from("quiz_attempts").insert({ user_id: userId, quiz_id: input.quizId ?? null, level: input.level ?? null, skill: input.skill ?? null, total_questions: input.total, correct_count: input.correct, score, xp_earned: xpEarned, duration_seconds: input.durationSeconds, completed_at: new Date().toISOString() }).select("id").maybeSingle(); if (error || !attempt) return; await supabase.from("quiz_answers").insert(input.answers.map(a => ({ attempt_id: attempt.id, user_id: userId, question_id: a.questionId, selected_index: a.selectedIndex, is_correct: a.isCorrect }))); await supabase.rpc("record_learning_activity", { p_activity_type: input.quizId?.startsWith("fallback-") ? "simulation_completed" : "quiz_completed", p_content_type: input.skill ?? "quiz", p_content_id: input.quizId ?? null, p_points: xpEarned, p_xp: xpEarned, p_correct: null, p_duration_seconds: input.durationSeconds, p_metadata: { level: input.level ?? null, total: input.total, correct: input.correct, score } }); for (const answer of input.answers) { await supabase.rpc("record_learning_activity", { p_activity_type: "quiz_answered", p_content_type: input.skill ?? "quiz", p_content_id: answer.questionId, p_points: answer.isCorrect ? 10 : 0, p_xp: answer.isCorrect ? 10 : 0, p_correct: answer.isCorrect, p_duration_seconds: 0, p_metadata: { quiz_id: input.quizId ?? null, level: input.level ?? null } }); } }
export async function markItemLearned(input: { itemType: "kanji" | "vocabulary" | "grammar"; itemId: string; level: Level }) { const { data: userRes } = await supabase.auth.getUser(); const userId = userRes.user?.id; if (!userId) throw new Error("Sesi tidak ditemukan."); const { data: existing } = await supabase.from("user_item_progress").select("id, repetitions").eq("user_id", userId).eq("item_type", input.itemType).eq("item_id", input.itemId).maybeSingle(); const due = new Date(); due.setDate(due.getDate() + 1); if (existing) { const { error } = await supabase.from("user_item_progress").update({ status: "learning", repetitions: (existing.repetitions ?? 0) + 1, last_reviewed_at: new Date().toISOString(), due_at: due.toISOString() }).eq("id", existing.id); if (error) throw new Error(error.message); await supabase.rpc("record_learning_activity", { p_activity_type: "lesson_completed", p_content_type: input.itemType, p_content_id: input.itemId, p_points: 5, p_xp: 5, p_correct: null, p_duration_seconds: 60, p_metadata: { level: input.level, repetition: (existing.repetitions ?? 0) + 1 } }); return; } const { error } = await supabase.from("user_item_progress").insert({ user_id: userId, item_type: input.itemType, item_id: input.itemId, level: input.level, status: "learning", repetitions: 1, last_reviewed_at: new Date().toISOString(), due_at: due.toISOString() }); if (error) throw new Error(error.message); await supabase.rpc("record_learning_activity", { p_activity_type: "lesson_completed", p_content_type: input.itemType, p_content_id: input.itemId, p_points: 5, p_xp: 5, p_correct: null, p_duration_seconds: 60, p_metadata: { level: input.level, repetition: 1 } }); }
export async function fetchMyProgress() { const { data: userRes } = await supabase.auth.getUser(); const userId = userRes.user?.id; if (!userId) return null; const [progress, stats, attempts, answers] = await Promise.all([supabase.from("user_item_progress").select("item_type, level, status").eq("user_id", userId), supabase.from("user_stats").select("*").eq("user_id", userId).maybeSingle(), supabase.from("quiz_attempts").select("id, level, skill, score, correct_count, total_questions, created_at").eq("user_id", userId).order("created_at", { ascending: false }).limit(10), supabase.from("quiz_answers").select("is_correct, question:question_id (skill, prompt)").eq("user_id", userId).eq("is_correct", false).limit(50)]); return { progress: progress.data ?? [], stats: stats.data, attempts: attempts.data ?? [], weak: (answers.data ?? []) as Array<{ question: { skill: string; prompt: string } | null }> }; }
export async function fetchContentTotals() { const [kanji, vocab, grammar, reading, listening] = await Promise.all([supabase.from("kanji").select("id", { count: "exact", head: true }).eq("is_published", true), supabase.from("vocabulary").select("id", { count: "exact", head: true }).eq("is_published", true), supabase.from("grammar_points").select("id", { count: "exact", head: true }).eq("is_published", true), supabase.from("reading_passages").select("id", { count: "exact", head: true }).eq("is_published", true), supabase.from("listening_items").select("id", { count: "exact", head: true }).eq("is_published", true)]); return { kanji: kanji.count ?? 0, vocabulary: vocab.count ?? 0, grammar: grammar.count ?? 0, reading: reading.count ?? 0, listening: listening.count ?? 0 }; }
export async function fetchRewards() { const { data: userRes } = await supabase.auth.getUser(); const userId = userRes.user?.id; if (!userId) return null; const [profile, stats, referrals, grants] = await Promise.all([supabase.from("profiles").select("referral_code, display_name").eq("id", userId).maybeSingle(), supabase.from("user_stats").select("reward_points, total_xp, current_streak").eq("user_id", userId).maybeSingle(), supabase.from("referrals").select("id, code, status, points_awarded, created_at").eq("referrer_id", userId).order("created_at", { ascending: false }), supabase.from("reward_grants").select("id, reward_kind, premium_days, points_spent, created_at").eq("user_id", userId).order("created_at", { ascending: false })]); return { referralCode: profile.data?.referral_code ?? null, points: stats.data?.reward_points ?? 0, xp: stats.data?.total_xp ?? 0, streak: stats.data?.current_streak ?? 0, referrals: referrals.data ?? [], grants: grants.data ?? [] }; }
