import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Check, ChevronDown, Pause, Play, Volume2 } from "lucide-react";
import { AppShell } from "@/components/layout/AppShell";
import { Button } from "@/components/ui/button";
import { fetchPassageDetail, type Level } from "@/lib/learn-queries";
import { markContentMastered } from "@/lib/progress-actions";

export const Route = createFileRoute("/_authenticated/dokkai/$id")({ component: DokkaiDetail });
type FuriganaPassage = { body_furigana?: string | null; difficulty?: string | null; category?: string | null };
type PassageQuestion = { id: string; prompt: string; choices: string[]; correct_index: number; explanation_id?: string | null };

function renderFurigana(text:string){return text.split(/(\[[^|\]]+\|[^\]]+\])/g).map((part,index)=>{const m=part.match(/^\[([^|\]]+)\|([^|\]]+)\]$/);return m?<ruby key={index}>{m[1]}<rt className="text-[0.46em] font-normal tracking-normal">{m[2]}</rt></ruby>:<span key={index}>{part}</span>})}
function normalizeBreaks(text:string){return text.replace(/\\r\\n/g,"\n").replace(/\\n/g,"\n").replace(/\r\n/g,"\n")}
function splitParagraphs(text:string){const normalized=normalizeBreaks(text).trim();if(!normalized)return[];const byBlank=normalized.split(/\n\s*\n/).map(x=>x.trim()).filter(Boolean);return byBlank.length>1?byBlank:normalized.split(/\n/).map(x=>x.trim()).filter(Boolean)}
function cleanJapanese(text:string){return normalizeBreaks(text).replace(/\[([^|\]]+)\|[^\]]+\]/g,"$1")}
function speakJapanese(text:string,onEnd?:()=>void){if(typeof window==="undefined"||!("speechSynthesis" in window))return false;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(cleanJapanese(text));u.lang="ja-JP";u.rate=.86;if(onEnd)u.onend=onEnd;window.speechSynthesis.speak(u);return true}

function DokkaiDetail(){
 const{id}=Route.useParams();const qc=useQueryClient();const{data,isLoading,error}=useQuery({queryKey:["passage",id],queryFn:()=>fetchPassageDetail(id)});const[showFurigana,setShowFurigana]=useState(true);const[fontSize,setFontSize]=useState(1);const[speakingIndex,setSpeakingIndex]=useState<number|null>(null);const[answers,setAnswers]=useState<Record<string,number>>({});const[checked,setChecked]=useState(false);const[completed,setCompleted]=useState(false);
 useEffect(()=>()=>{if(typeof window!=="undefined"&&"speechSynthesis" in window)window.speechSynthesis.cancel()},[]);
 const p=data?.passage;const enriched=p as (typeof p&FuriganaPassage)|null|undefined;const questions=(data?.questions??[]) as PassageQuestion[];
 const body=useMemo(()=>normalizeBreaks(String(p?.body_jp??"")),[p?.body_jp]);const furiganaBody=useMemo(()=>normalizeBreaks(String(enriched?.body_furigana??"")),[enriched?.body_furigana]);const paragraphs=useMemo(()=>splitParagraphs(body),[body]);const furiganaParagraphs=useMemo(()=>splitParagraphs(furiganaBody),[furiganaBody]);
 const completeMutation=useMutation({mutationFn:()=>markContentMastered({itemType:"reading",itemId:id,level:String(p?.level??"N5") as Level,durationSeconds:Math.max(60,Number(p?.estimated_minutes??1)*60)}),onSuccess:()=>{setCompleted(true);void qc.invalidateQueries({queryKey:["dashboard-live"]});void qc.invalidateQueries({queryKey:["my-progress"]})}});
 const readParagraph=(text:string,index:number)=>{if(speakingIndex===index){window.speechSynthesis.cancel();setSpeakingIndex(null);return}if(speakJapanese(text,()=>setSpeakingIndex(null)))setSpeakingIndex(index)};
 const checkAnswers=()=>{setChecked(true);if(!completeMutation.isPending)completeMutation.mutate()};
 if(isLoading)return <AppShell title="Dokkai"><p className="text-[12px] text-muted-foreground">Memuat bacaan…</p></AppShell>;
 if(error||!p)return <AppShell title="Dokkai"><p className="text-[12px] text-destructive">Bacaan tidak ditemukan atau gagal dimuat.</p></AppShell>;
 return <AppShell title="Dokkai" compact><div className="mx-auto w-full max-w-md pb-8">
  <div className="mb-3 flex items-center justify-between"><a href="/dokkai" className="inline-flex items-center gap-1.5 text-[11px] font-semibold"><ArrowLeft className="size-4"/>Dokkai {p.level}</a><span className="text-[10px] font-semibold text-muted-foreground">{paragraphs.length||1} bagian</span></div>
  <div className="mb-2 flex items-start justify-between gap-3"><div className="min-w-0"><h1 lang="ja" className="font-jp text-[21px] font-bold leading-7">{p.title}</h1><p className="mt-1 text-[9px] text-muted-foreground">文章の長さ：{enriched?.difficulty||enriched?.category||"中級"}</p></div><div className="flex shrink-0 items-center gap-1"><span className="text-[9px] text-muted-foreground">Furigana</span><button type="button" onClick={()=>setShowFurigana(v=>!v)} className={`rounded-full px-2 py-1 text-[9px] font-bold ${showFurigana?"bg-primary text-primary-foreground":"border bg-background"}`}>{showFurigana?"ON":"OFF"}</button></div></div>
  <div className="mb-3 flex items-center justify-end gap-1"><button onClick={()=>setFontSize(v=>Math.max(.82,Number((v-.1).toFixed(2))))} className="grid size-7 place-items-center rounded-full border text-[9px]">A−</button><button onClick={()=>setFontSize(1)} className="grid size-7 place-items-center rounded-full border text-[9px]">A</button><button onClick={()=>setFontSize(v=>Math.min(1.3,Number((v+.1).toFixed(2))))} className="grid size-7 place-items-center rounded-full border text-[9px]">A+</button></div>
  <article lang="ja" className="font-jp overflow-visible rounded-none bg-transparent p-0 text-foreground" style={{fontSize:`${fontSize}rem`}}>
   {paragraphs.length?paragraphs.map((paragraph,index)=>{const reading=showFurigana&&furiganaParagraphs[index]?furiganaParagraphs[index]:paragraph;return <section key={index} className="mb-3 last:mb-0"><div className="flex items-start gap-2"><p className="min-w-0 flex-1 whitespace-pre-wrap break-words leading-[1.9] tracking-[0.01em]">{showFurigana&&furiganaParagraphs[index]?renderFurigana(reading):reading}</p><button type="button" aria-label={`Dengarkan paragraf ${index+1}`} onClick={()=>readParagraph(furiganaParagraphs[index]||paragraph,index)} className="mt-1 grid size-7 shrink-0 place-items-center rounded-full text-primary hover:bg-primary/10">{speakingIndex===index?<Pause className="size-3.5"/>:<Volume2 className="size-3.5"/>}</button></div></section>}):<div className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-[11px] leading-5 text-amber-800">Teks bacaan lengkap belum tersedia pada data materi ini.</div>}
  </article>
  <div className="mt-5 space-y-2">
   <details className="group rounded-xl border bg-card px-3 py-2.5"><summary className="flex cursor-pointer list-none items-center justify-between text-[11px] font-semibold">Arti Seluruh Bagian<ChevronDown className="size-4 transition group-open:rotate-180"/></summary><p className="mt-3 whitespace-pre-wrap break-words text-[11px] leading-6 text-muted-foreground">{normalizeBreaks(String(p.translation_id||"Terjemahan Indonesia belum tersedia."))}</p></details>
   <details className="group rounded-xl border bg-card px-3 py-2.5"><summary className="flex cursor-pointer list-none items-center justify-between text-[11px] font-semibold">Pertanyaan<ChevronDown className="size-4 transition group-open:rotate-180"/></summary><div className="mt-3 space-y-4">{questions.length===0?<p className="text-[10px] text-muted-foreground">Belum ada soal untuk bacaan ini.</p>:questions.map((q,i)=><div key={q.id}><p className="text-[11px] font-semibold">{i+1}. {q.prompt}</p><div className="mt-2 space-y-1.5">{q.choices.map((choice,ci)=><button key={ci} type="button" onClick={()=>{setAnswers(a=>({...a,[q.id]:ci}));setChecked(false)}} className={`w-full rounded-lg border px-3 py-2 text-left text-[10px] ${answers[q.id]===ci?"border-primary bg-primary/5":"bg-background"}`}>{String.fromCharCode(65+ci)}. {choice}</button>)}</div>{checked&&answers[q.id]!==undefined&&<p className="mt-2 text-[9px] text-muted-foreground">{answers[q.id]===Number(q.correct_index)?"Benar.":q.explanation_id||"Belum tepat. Baca kembali bagian terkait."}</p>}</div>)}{questions.length>0&&<Button className="h-9 w-full rounded-full text-[10px]" disabled={Object.keys(answers).length!==questions.length||completeMutation.isPending} onClick={checkAnswers}>{completed?<><Check className="mr-1.5 size-3.5"/>Selesai</>:"Periksa Jawaban"}</Button>}</div></details>
   <details className="group rounded-xl border bg-card px-3 py-2.5"><summary className="flex cursor-pointer list-none items-center justify-between text-[11px] font-semibold">Kosakata Penting<ChevronDown className="size-4 transition group-open:rotate-180"/></summary><p className="mt-3 text-[10px] leading-5 text-muted-foreground">Kosakata penting dari bacaan akan ditampilkan ketika data anotasi tersedia.</p></details>
  </div>
  {questions.length===0&&<Button className="mt-4 h-10 w-full rounded-full text-[10px]" disabled={completed||completeMutation.isPending||!paragraphs.length} onClick={()=>completeMutation.mutate()}>{completed?<><Check className="mr-1.5 size-4"/>Selesai dibaca</>:"Tandai selesai membaca · +5 XP"}</Button>}
 </div></AppShell>
}
