import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { AppShell } from "@/components/layout/AppShell";
import { LevelTabs } from "@/components/learn/LevelTabs";
import { StudyFlashcard } from "@/components/learn/StudyFlashcard";
import { fetchKanjiList, markItemLearned, type Level } from "@/lib/learn-queries";
export const Route = createFileRoute("/_authenticated/kanji")({ component: KanjiPage });
function KanjiPage(){const[level,setLevel]=useState<Level>("N5");const[index,setIndex]=useState(0);const[learned,setLearned]=useState<Record<string,boolean>>({});const qc=useQueryClient();const{data,isLoading,error}=useQuery({queryKey:["kanji",level],queryFn:()=>fetchKanjiList(level)});const mutation=useMutation({mutationFn:(id:string)=>markItemLearned({itemType:"kanji",itemId:id,level}),onSuccess:(_,id)=>{setLearned(x=>({...x,[id]:true}));void qc.invalidateQueries({queryKey:["my-progress"]})}});const cards=data??[];const item=cards[index];const meaning=(item?.meaning_id||item?.meaning_en||"Arti belum tersedia") as string;const choices=item?[meaning,...cards.filter((x:any)=>x.id!==item.id&&x.meaning_id).slice(0,3).map((x:any)=>x.meaning_id)]:[];return <AppShell title="漢字 · Kanji" description="Belajar kanji dengan kartu interaktif: arti, bacaan, penjelasan, dan cek pemahaman." backTo="/belajar" backLabel="Belajar"><LevelTabs value={level} onChange={v=>{setLevel(v);setIndex(0)}}/>{error&&<p className="mt-5 text-sm text-destructive">Gagal memuat kanji. Coba refresh.</p>}{isLoading&&<p className="mt-8 text-center text-sm text-muted-foreground">Memuat materi…</p>}{item&&<div className="mt-6"><StudyFlashcard index={index} total={cards.length} level={item.level} title={item.character} reading={[...(item.onyomi??[]),...(item.kunyomi??[])].join("・")} meaning={meaning} secondary={item.stroke_count?`${item.stroke_count} coretan`:null} explanation="Kenali bentuk kanji, hafalkan arti utama, lalu perhatikan bacaannya. Gunakan cek pemahaman sebelum pindah kartu." question={choices.length>1?{prompt:`Apa arti kanji ${item.character}?`,choices,correctIndex:0}:null} learned={!!learned[item.id]} onLearned={()=>mutation.mutate(item.id)} onPrev={()=>setIndex(i=>Math.max(0,i-1))} onNext={()=>setIndex(i=>Math.min(cards.length-1,i+1))}/></div>}{!isLoading&&!cards.length&&<p className="mt-8 text-center text-sm text-muted-foreground">Belum ada kanji terbit untuk {level}.</p>}</AppShell>}
