import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { AppShell } from "@/components/layout/AppShell";
import { LevelTabs } from "@/components/learn/LevelTabs";
import { StudyFlashcard } from "@/components/learn/StudyFlashcard";
import { fetchVocabList, markItemLearned, asExamples, type Level } from "@/lib/learn-queries";
export const Route = createFileRoute("/_authenticated/kotoba")({component:KotobaPage});
function KotobaPage(){const[level,setLevel]=useState<Level>("N5");const[index,setIndex]=useState(0);const[learned,setLearned]=useState<Record<string,boolean>>({});const qc=useQueryClient();const{data,isLoading,error}=useQuery({queryKey:["vocab",level],queryFn:()=>fetchVocabList(level)});const mutation=useMutation({mutationFn:(id:string)=>markItemLearned({itemType:"vocabulary",itemId:id,level}),onSuccess:(_,id)=>{setLearned(x=>({...x,[id]:true}));void qc.invalidateQueries({queryKey:["my-progress"]})}});const cards=data??[];const item=cards[index];const examples=item?asExamples(item.examples):[];const meaning=item?.meaning_id||item?.meaning_en||"Arti belum tersedia";const choices=item?[meaning,...cards.filter((x:any)=>x.id!==item.id&&x.meaning_id).slice(0,3).map((x:any)=>x.meaning_id)]:[];return <AppShell title="言葉 · Kotoba" description="Kartu kosakata dengan bacaan, arti, contoh kalimat, dan cek pemahaman." backTo="/belajar" backLabel="Belajar"><LevelTabs value={level} onChange={v=>{setLevel(v);setIndex(0)}}/>{error&&<p className="mt-5 text-sm text-destructive">Gagal memuat kosakata. Coba refresh.</p>}{isLoading&&<p className="mt-8 text-center text-sm text-muted-foreground">Memuat kosakata…</p>}{item&&<div className="mt-6"><StudyFlashcard index={index} total={cards.length} level={item.level} title={item.term} reading={item.reading} meaning={meaning} secondary={item.romaji||item.part_of_speech} explanation={`Pahami arti ${item.term} melalui konteks. Perhatikan bacaan, kelas kata, dan contoh kalimat.`} examples={examples} question={choices.length>1?{prompt:`Apa arti kosakata ${item.term}?`,choices,correctIndex:0}:null} learned={!!learned[item.id]} onLearned={()=>mutation.mutate(item.id)} onPrev={()=>setIndex(i=>Math.max(0,i-1))} onNext={()=>setIndex(i=>Math.min(cards.length-1,i+1))}/></div>}{!isLoading&&!cards.length&&<p className="mt-8 text-center text-sm text-muted-foreground">Belum ada kosakata terbit untuk {level}.</p>}</AppShell>}
