import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { Crown, Flame, Gift, Medal, Trophy, Sparkles, LockKeyhole } from "lucide-react";
import { AppShell } from "@/components/layout/AppShell";
import { Card, CardContent } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { fetchCompetitionLeaderboard, fetchLeaderboard } from "@/lib/leaderboard";
import { getLeague, LEAGUES } from "@/lib/progression";
import { supabase } from "@/integrations/supabase/client";

export const Route=createFileRoute("/_authenticated/leaderboard")({head:()=>({meta:[{title:"Leaderboard — ENO NIHONGO"}]}),component:LeaderboardPage});
function LeaderboardPage(){
 const leaderboard=useQuery({queryKey:["leaderboard",50],queryFn:()=>fetchLeaderboard(50),staleTime:30000});
 const weeklyRanks=useQuery({queryKey:["competition-leaderboard","weekly"],queryFn:()=>fetchCompetitionLeaderboard("weekly",50),staleTime:30000});
 const me=useQuery({queryKey:["auth-user-id"],queryFn:async()=>(await supabase.auth.getUser()).data.user?.id??null,staleTime:60000});
 const myWeeklyRow=weeklyRanks.data?.find(u=>u.userId===me.data);const myLeague=getLeague(myWeeklyRow?.periodXp??0);
 return <AppShell compact title="Leaderboard"><div className="mx-auto max-w-3xl space-y-4 eno-rise">
  <section className="flex items-start justify-between gap-3"><div><p className="text-[11px] font-semibold uppercase tracking-[.12em] text-primary">Kompetisi Sehat</p><h1 className="mt-1 text-[20px] font-bold">Leaderboard</h1><p className="mt-1 text-[11px] text-muted-foreground">Peringkat utama berdasarkan total Poin yang diperoleh.</p></div><span className="eno-pop grid size-10 place-items-center rounded-2xl bg-amber-500/10 text-amber-600"><Trophy className="size-5"/></span></section>
  <Card className="rounded-2xl border-primary/20 bg-primary/[.04]"><CardContent className="flex items-center gap-3 p-4"><span className="eno-pulse-soft grid size-10 place-items-center rounded-xl bg-primary/10 text-primary"><Sparkles className="size-5"/></span><div className="min-w-0 flex-1"><p className="text-[12px] font-bold">Tukar Poin Premium</p><p className="mt-1 text-[9px] leading-4 text-muted-foreground">Tukar Poin menjadi akses Premium. Fitur penukaran akan dibuka segera.</p></div><span className="inline-flex items-center gap-1 rounded-full border px-2 py-1 text-[9px] font-semibold text-muted-foreground"><LockKeyhole className="size-3"/>Segera</span></CardContent></Card>
  <Card className="rounded-2xl"><CardContent className="p-2">{leaderboard.isLoading?<div className="space-y-2 p-2"><Skeleton className="h-12 w-full"/><Skeleton className="h-12 w-full"/></div>:leaderboard.data?.length?leaderboard.data.map((user,i)=><div key={user.userId} className="flex items-center gap-3 rounded-xl px-3 py-2.5 hover:bg-muted/40 eno-rise" style={{animationDelay:`${Math.min(i,8)*28}ms`}}><span className="grid size-7 place-items-center rounded-lg bg-muted text-[11px] font-bold">{user.rank<=3?<Medal className={user.rank===1?"size-4 text-amber-500":user.rank===2?"size-4 text-slate-400":"size-4 text-orange-600"}/>:user.rank}</span>{user.avatarUrl?<img src={user.avatarUrl} alt="" className="size-8 rounded-full border object-cover"/>:null}<div className="min-w-0 flex-1"><p className="truncate text-[11px] font-semibold">{user.displayName}</p><p className="text-[9px] text-muted-foreground">{user.level} · Streak {user.streak} hari</p></div><span className="text-[11px] font-bold text-primary">{user.points.toLocaleString("id-ID")} Poin</span></div>):<p className="py-8 text-center text-[11px] text-muted-foreground">Belum ada aktivitas.</p>}</CardContent></Card>
  <section><h2 className="mb-2 px-1 text-[13px] font-semibold">Liga Mingguan</h2><Card className="rounded-2xl"><CardContent className="p-4"><div className="flex items-center justify-between gap-2 text-center">{LEAGUES.map((league,index)=><div key={league.name} className="min-w-0 flex-1"><span className={myLeague.index===index?"eno-bounce mx-auto grid size-8 place-items-center rounded-full bg-primary text-[9px] font-bold text-primary-foreground":"mx-auto grid size-8 place-items-center rounded-full bg-muted text-[9px] font-bold text-muted-foreground"}>{index+1}</span><p className="mt-1 truncate text-[8px] font-medium">{league.name}</p><p className="text-[7px] text-muted-foreground">{league.minWeeklyXp.toLocaleString("id-ID")} Poin+</p><p className="mt-0.5 text-[7px] font-semibold text-primary">🎁 {league.rewardLabel}</p></div>)}</div><div className="mt-4 rounded-xl bg-primary/[.05] p-3"><div className="flex items-center justify-between"><div><p className="text-[11px] font-bold">Liga kamu: {myLeague.name}</p><p className="mt-.5 text-[9px] text-muted-foreground">Reset Senin 00:00 JST.</p></div><Crown className="eno-pop size-5 text-amber-500"/></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-muted"><div className="eno-progress h-full rounded-full bg-primary" style={{width:`${myLeague.progress}%`}}/></div><p className="mt-1.5 text-[9px] text-muted-foreground">{myLeague.next?`${myLeague.xpToNext.toLocaleString("id-ID")} Poin lagi ke ${myLeague.next.name}`:"Liga tertinggi tercapai."}</p><div className="eno-pop mt-2 flex items-center gap-2 rounded-lg border border-primary/15 bg-background/80 px-2.5 py-2"><Gift className="size-3.5 text-primary"/><div><p className="text-[9px] font-semibold">Hadiah liga kamu</p><p className="text-[10px] font-bold text-primary">{myLeague.rewardLabel} setiap akhir minggu</p></div></div></div><div className="mt-3 space-y-1 text-[9px] leading-4 text-muted-foreground"><p>• Bronze 0–1.499 · Silver 1.500–3.499 · Gold 3.500–6.999 Poin/minggu.</p><p>• Platinum 7.000–11.999 · Diamond 12.000+ Poin/minggu.</p></div></CardContent></Card></section>
  <Card className="rounded-2xl border-amber-500/20 bg-amber-500/[.04]"><CardContent className="flex gap-3 p-4"><Flame className="eno-pulse-soft mt-.5 size-4 text-orange-500"/><p className="text-[10px] leading-5 text-muted-foreground">Hadiah liga diberikan berdasarkan liga yang dicapai pada akhir periode mingguan.</p></CardContent></Card>
 </div></AppShell>;
}
