/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedBelajarRouteImport } from './routes/_authenticated/belajar'
import { Route as AuthenticatedBunpoRouteImport } from './routes/_authenticated/bunpo'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDokkaiRouteImport } from './routes/_authenticated/dokkai'
import { Route as AuthenticatedKanjiRouteImport } from './routes/_authenticated/kanji'
import { Route as AuthenticatedKotobaRouteImport } from './routes/_authenticated/kotoba'
import { Route as AuthenticatedListeningRouteImport } from './routes/_authenticated/listening'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedQuizRouteImport } from './routes/_authenticated/quiz'
import { Route as AuthenticatedReferralRouteImport } from './routes/_authenticated/referral'
import { Route as AuthenticatedDokkaiIdRouteImport } from './routes/_authenticated/dokkai/$id'
import { Route as AuthenticatedKanjiIdRouteImport } from './routes/_authenticated/kanji/$id'
import { Route as AuthenticatedQuizSlugRouteImport } from './routes/_authenticated/quiz/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBelajarRoute = AuthenticatedBelajarRouteImport.update({
  id: '/belajar',
  path: '/belajar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBunpoRoute = AuthenticatedBunpoRouteImport.update({
  id: '/bunpo',
  path: '/bunpo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDokkaiRoute = AuthenticatedDokkaiRouteImport.update({
  id: '/dokkai',
  path: '/dokkai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKanjiRoute = AuthenticatedKanjiRouteImport.update({
  id: '/kanji',
  path: '/kanji',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKotobaRoute = AuthenticatedKotobaRouteImport.update({
  id: '/kotoba',
  path: '/kotoba',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedListeningRoute = AuthenticatedListeningRouteImport.update({
  id: '/listening',
  path: '/listening',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuizRoute = AuthenticatedQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReferralRoute = AuthenticatedReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDokkaiIdRoute = AuthenticatedDokkaiIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedDokkaiRoute,
} as any)
const AuthenticatedKanjiIdRoute = AuthenticatedKanjiIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedKanjiRoute,
} as any)
const AuthenticatedQuizSlugRoute = AuthenticatedQuizSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AuthenticatedQuizRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/belajar': typeof AuthenticatedBelajarRoute
  '/bunpo': typeof AuthenticatedBunpoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dokkai': typeof AuthenticatedDokkaiRouteWithChildren
  '/kanji': typeof AuthenticatedKanjiRouteWithChildren
  '/kotoba': typeof AuthenticatedKotobaRoute
  '/listening': typeof AuthenticatedListeningRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/quiz': typeof AuthenticatedQuizRouteWithChildren
  '/referral': typeof AuthenticatedReferralRoute
  '/dokkai/$id': typeof AuthenticatedDokkaiIdRoute
  '/kanji/$id': typeof AuthenticatedKanjiIdRoute
  '/quiz/$slug': typeof AuthenticatedQuizSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/belajar': typeof AuthenticatedBelajarRoute
  '/bunpo': typeof AuthenticatedBunpoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dokkai': typeof AuthenticatedDokkaiRouteWithChildren
  '/kanji': typeof AuthenticatedKanjiRouteWithChildren
  '/kotoba': typeof AuthenticatedKotobaRoute
  '/listening': typeof AuthenticatedListeningRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/quiz': typeof AuthenticatedQuizRouteWithChildren
  '/referral': typeof AuthenticatedReferralRoute
  '/dokkai/$id': typeof AuthenticatedDokkaiIdRoute
  '/kanji/$id': typeof AuthenticatedKanjiIdRoute
  '/quiz/$slug': typeof AuthenticatedQuizSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/belajar': typeof AuthenticatedBelajarRoute
  '/_authenticated/bunpo': typeof AuthenticatedBunpoRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dokkai': typeof AuthenticatedDokkaiRouteWithChildren
  '/_authenticated/kanji': typeof AuthenticatedKanjiRouteWithChildren
  '/_authenticated/kotoba': typeof AuthenticatedKotobaRoute
  '/_authenticated/listening': typeof AuthenticatedListeningRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/quiz': typeof AuthenticatedQuizRouteWithChildren
  '/_authenticated/referral': typeof AuthenticatedReferralRoute
  '/_authenticated/dokkai/$id': typeof AuthenticatedDokkaiIdRoute
  '/_authenticated/kanji/$id': typeof AuthenticatedKanjiIdRoute
  '/_authenticated/quiz/$slug': typeof AuthenticatedQuizSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/belajar'
    | '/bunpo'
    | '/dashboard'
    | '/dokkai'
    | '/kanji'
    | '/kotoba'
    | '/listening'
    | '/profil'
    | '/progress'
    | '/quiz'
    | '/referral'
    | '/dokkai/$id'
    | '/kanji/$id'
    | '/quiz/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/belajar'
    | '/bunpo'
    | '/dashboard'
    | '/dokkai'
    | '/kanji'
    | '/kotoba'
    | '/listening'
    | '/profil'
    | '/progress'
    | '/quiz'
    | '/referral'
    | '/dokkai/$id'
    | '/kanji/$id'
    | '/quiz/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/belajar'
    | '/_authenticated/bunpo'
    | '/_authenticated/dashboard'
    | '/_authenticated/dokkai'
    | '/_authenticated/kanji'
    | '/_authenticated/kotoba'
    | '/_authenticated/listening'
    | '/_authenticated/profil'
    | '/_authenticated/progress'
    | '/_authenticated/quiz'
    | '/_authenticated/referral'
    | '/_authenticated/dokkai/$id'
    | '/_authenticated/kanji/$id'
    | '/_authenticated/quiz/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/belajar': {
      id: '/_authenticated/belajar'
      path: '/belajar'
      fullPath: '/belajar'
      preLoaderRoute: typeof AuthenticatedBelajarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bunpo': {
      id: '/_authenticated/bunpo'
      path: '/bunpo'
      fullPath: '/bunpo'
      preLoaderRoute: typeof AuthenticatedBunpoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dokkai': {
      id: '/_authenticated/dokkai'
      path: '/dokkai'
      fullPath: '/dokkai'
      preLoaderRoute: typeof AuthenticatedDokkaiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kanji': {
      id: '/_authenticated/kanji'
      path: '/kanji'
      fullPath: '/kanji'
      preLoaderRoute: typeof AuthenticatedKanjiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kotoba': {
      id: '/_authenticated/kotoba'
      path: '/kotoba'
      fullPath: '/kotoba'
      preLoaderRoute: typeof AuthenticatedKotobaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/listening': {
      id: '/_authenticated/listening'
      path: '/listening'
      fullPath: '/listening'
      preLoaderRoute: typeof AuthenticatedListeningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quiz': {
      id: '/_authenticated/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof AuthenticatedQuizRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referral': {
      id: '/_authenticated/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof AuthenticatedReferralRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dokkai/$id': {
      id: '/_authenticated/dokkai/$id'
      path: '/$id'
      fullPath: '/dokkai/$id'
      preLoaderRoute: typeof AuthenticatedDokkaiIdRouteImport
      parentRoute: typeof AuthenticatedDokkaiRoute
    }
    '/_authenticated/kanji/$id': {
      id: '/_authenticated/kanji/$id'
      path: '/$id'
      fullPath: '/kanji/$id'
      preLoaderRoute: typeof AuthenticatedKanjiIdRouteImport
      parentRoute: typeof AuthenticatedKanjiRoute
    }
    '/_authenticated/quiz/$slug': {
      id: '/_authenticated/quiz/$slug'
      path: '/$slug'
      fullPath: '/quiz/$slug'
      preLoaderRoute: typeof AuthenticatedQuizSlugRouteImport
      parentRoute: typeof AuthenticatedQuizRoute
    }
  }
}

interface AuthenticatedDokkaiRouteChildren {
  AuthenticatedDokkaiIdRoute: typeof AuthenticatedDokkaiIdRoute
}

const AuthenticatedDokkaiRouteChildren: AuthenticatedDokkaiRouteChildren = {
  AuthenticatedDokkaiIdRoute: AuthenticatedDokkaiIdRoute,
}

const AuthenticatedDokkaiRouteWithChildren =
  AuthenticatedDokkaiRoute._addFileChildren(AuthenticatedDokkaiRouteChildren)

interface AuthenticatedKanjiRouteChildren {
  AuthenticatedKanjiIdRoute: typeof AuthenticatedKanjiIdRoute
}

const AuthenticatedKanjiRouteChildren: AuthenticatedKanjiRouteChildren = {
  AuthenticatedKanjiIdRoute: AuthenticatedKanjiIdRoute,
}

const AuthenticatedKanjiRouteWithChildren =
  AuthenticatedKanjiRoute._addFileChildren(AuthenticatedKanjiRouteChildren)

interface AuthenticatedQuizRouteChildren {
  AuthenticatedQuizSlugRoute: typeof AuthenticatedQuizSlugRoute
}

const AuthenticatedQuizRouteChildren: AuthenticatedQuizRouteChildren = {
  AuthenticatedQuizSlugRoute: AuthenticatedQuizSlugRoute,
}

const AuthenticatedQuizRouteWithChildren =
  AuthenticatedQuizRoute._addFileChildren(AuthenticatedQuizRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBelajarRoute: typeof AuthenticatedBelajarRoute
  AuthenticatedBunpoRoute: typeof AuthenticatedBunpoRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDokkaiRoute: typeof AuthenticatedDokkaiRouteWithChildren
  AuthenticatedKanjiRoute: typeof AuthenticatedKanjiRouteWithChildren
  AuthenticatedKotobaRoute: typeof AuthenticatedKotobaRoute
  AuthenticatedListeningRoute: typeof AuthenticatedListeningRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedQuizRoute: typeof AuthenticatedQuizRouteWithChildren
  AuthenticatedReferralRoute: typeof AuthenticatedReferralRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBelajarRoute: AuthenticatedBelajarRoute,
  AuthenticatedBunpoRoute: AuthenticatedBunpoRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDokkaiRoute: AuthenticatedDokkaiRouteWithChildren,
  AuthenticatedKanjiRoute: AuthenticatedKanjiRouteWithChildren,
  AuthenticatedKotobaRoute: AuthenticatedKotobaRoute,
  AuthenticatedListeningRoute: AuthenticatedListeningRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedQuizRoute: AuthenticatedQuizRouteWithChildren,
  AuthenticatedReferralRoute: AuthenticatedReferralRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
