/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is generated by TanStack Router and checked in so production builds
// always use the same route manifest as the source tree.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedBelajarRouteImport } from './routes/_authenticated/belajar'
import { Route as AuthenticatedBunpoRouteImport } from './routes/_authenticated/bunpo'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDokkaiRouteImport } from './routes/_authenticated/dokkai'
import { Route as AuthenticatedDokkaiIdRouteImport } from './routes/_authenticated/dokkai/$id'
import { Route as AuthenticatedKanjiRouteImport } from './routes/_authenticated/kanji'
import { Route as AuthenticatedKanjiIdRouteImport } from './routes/_authenticated/kanji/$id'
import { Route as AuthenticatedKotobaRouteImport } from './routes/_authenticated/kotoba'
import { Route as AuthenticatedListeningRouteImport } from './routes/_authenticated/listening'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedQuizRouteImport } from './routes/_authenticated/quiz'
import { Route as AuthenticatedQuizSlugRouteImport } from './routes/_authenticated/quiz/$slug'
import { Route as AuthenticatedReferralRouteImport } from './routes/_authenticated/referral'

const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({ id: '/_authenticated', getParentRoute: () => rootRouteImport } as any)
const AuthRoute = AuthRouteImport.update({ id: '/auth', path: '/auth', getParentRoute: () => rootRouteImport } as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({ id: '/reset-password', path: '/reset-password', getParentRoute: () => rootRouteImport } as any)

const AuthenticatedBelajarRoute = AuthenticatedBelajarRouteImport.update({ id: '/belajar', path: '/belajar', getParentRoute: () => AuthenticatedRouteRoute } as any)
const AuthenticatedBunpoRoute = AuthenticatedBunpoRouteImport.update({ id: '/bunpo', path: '/bunpo', getParentRoute: () => AuthenticatedRouteRoute } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({ id: '/dashboard', path: '/dashboard', getParentRoute: () => AuthenticatedRouteRoute } as any)
const AuthenticatedDokkaiRoute = AuthenticatedDokkaiRouteImport.update({ id: '/dokkai', path: '/dokkai', getParentRoute: () => AuthenticatedRouteRoute } as any)
const AuthenticatedDokkaiIdRoute = AuthenticatedDokkaiIdRouteImport.update({ id: '/dokkai/$id', path: '/dokkai/$id', getParentRoute: () => AuthenticatedRouteRoute } as any)
const AuthenticatedKanjiRoute = AuthenticatedKanjiRouteImport.update({ id: '/kanji', path: '/kanji', getParentRoute: () => AuthenticatedRouteRoute } as any)
const AuthenticatedKanjiIdRoute = AuthenticatedKanjiIdRouteImport.update({ id: '/kanji/$id', path: '/kanji/$id', getParentRoute: () => AuthenticatedRouteRoute } as any)
const AuthenticatedKotobaRoute = AuthenticatedKotobaRouteImport.update({ id: '/kotoba', path: '/kotoba', getParentRoute: () => AuthenticatedRouteRoute } as any)
const AuthenticatedListeningRoute = AuthenticatedListeningRouteImport.update({ id: '/listening', path: '/listening', getParentRoute: () => AuthenticatedRouteRoute } as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({ id: '/profil', path: '/profil', getParentRoute: () => AuthenticatedRouteRoute } as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({ id: '/progress', path: '/progress', getParentRoute: () => AuthenticatedRouteRoute } as any)
const AuthenticatedQuizRoute = AuthenticatedQuizRouteImport.update({ id: '/quiz', path: '/quiz', getParentRoute: () => AuthenticatedRouteRoute } as any)
const AuthenticatedQuizSlugRoute = AuthenticatedQuizSlugRouteImport.update({ id: '/quiz/$slug', path: '/quiz/$slug', getParentRoute: () => AuthenticatedRouteRoute } as any)
const AuthenticatedReferralRoute = AuthenticatedReferralRouteImport.update({ id: '/referral', path: '/referral', getParentRoute: () => AuthenticatedRouteRoute } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/belajar': typeof AuthenticatedBelajarRoute
  '/bunpo': typeof AuthenticatedBunpoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dokkai': typeof AuthenticatedDokkaiRoute
  '/dokkai/$id': typeof AuthenticatedDokkaiIdRoute
  '/kanji': typeof AuthenticatedKanjiRoute
  '/kanji/$id': typeof AuthenticatedKanjiIdRoute
  '/kotoba': typeof AuthenticatedKotobaRoute
  '/listening': typeof AuthenticatedListeningRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/quiz': typeof AuthenticatedQuizRoute
  '/quiz/$slug': typeof AuthenticatedQuizSlugRoute
  '/referral': typeof AuthenticatedReferralRoute
}
export interface FileRoutesByTo extends FileRoutesByFullPath {}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/belajar': typeof AuthenticatedBelajarRoute
  '/_authenticated/bunpo': typeof AuthenticatedBunpoRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dokkai': typeof AuthenticatedDokkaiRoute
  '/_authenticated/dokkai/$id': typeof AuthenticatedDokkaiIdRoute
  '/_authenticated/kanji': typeof AuthenticatedKanjiRoute
  '/_authenticated/kanji/$id': typeof AuthenticatedKanjiIdRoute
  '/_authenticated/kotoba': typeof AuthenticatedKotobaRoute
  '/_authenticated/listening': typeof AuthenticatedListeningRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/quiz': typeof AuthenticatedQuizRoute
  '/_authenticated/quiz/$slug': typeof AuthenticatedQuizSlugRoute
  '/_authenticated/referral': typeof AuthenticatedReferralRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: keyof FileRoutesByFullPath
  fileRoutesByTo: FileRoutesByTo
  to: keyof FileRoutesByTo
  id: keyof FileRoutesById
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/_authenticated': { id: '/_authenticated'; path: ''; fullPath: '/'; preLoaderRoute: typeof AuthenticatedRouteRouteImport; parentRoute: typeof rootRouteImport }
    '/auth': { id: '/auth'; path: '/auth'; fullPath: '/auth'; preLoaderRoute: typeof AuthRouteImport; parentRoute: typeof rootRouteImport }
    '/reset-password': { id: '/reset-password'; path: '/reset-password'; fullPath: '/reset-password'; preLoaderRoute: typeof ResetPasswordRouteImport; parentRoute: typeof rootRouteImport }
    '/_authenticated/belajar': { id: '/_authenticated/belajar'; path: '/belajar'; fullPath: '/belajar'; preLoaderRoute: typeof AuthenticatedBelajarRouteImport; parentRoute: typeof AuthenticatedRouteRoute }
    '/_authenticated/bunpo': { id: '/_authenticated/bunpo'; path: '/bunpo'; fullPath: '/bunpo'; preLoaderRoute: typeof AuthenticatedBunpoRouteImport; parentRoute: typeof AuthenticatedRouteRoute }
    '/_authenticated/dashboard': { id: '/_authenticated/dashboard'; path: '/dashboard'; fullPath: '/dashboard'; preLoaderRoute: typeof AuthenticatedDashboardRouteImport; parentRoute: typeof AuthenticatedRouteRoute }
    '/_authenticated/dokkai': { id: '/_authenticated/dokkai'; path: '/dokkai'; fullPath: '/dokkai'; preLoaderRoute: typeof AuthenticatedDokkaiRouteImport; parentRoute: typeof AuthenticatedRouteRoute }
    '/_authenticated/dokkai/$id': { id: '/_authenticated/dokkai/$id'; path: '/dokkai/$id'; fullPath: '/dokkai/$id'; preLoaderRoute: typeof AuthenticatedDokkaiIdRouteImport; parentRoute: typeof AuthenticatedRouteRoute }
    '/_authenticated/kanji': { id: '/_authenticated/kanji'; path: '/kanji'; fullPath: '/kanji'; preLoaderRoute: typeof AuthenticatedKanjiRouteImport; parentRoute: typeof AuthenticatedRouteRoute }
    '/_authenticated/kanji/$id': { id: '/_authenticated/kanji/$id'; path: '/kanji/$id'; fullPath: '/kanji/$id'; preLoaderRoute: typeof AuthenticatedKanjiIdRouteImport; parentRoute: typeof AuthenticatedRouteRoute }
    '/_authenticated/kotoba': { id: '/_authenticated/kotoba'; path: '/kotoba'; fullPath: '/kotoba'; preLoaderRoute: typeof AuthenticatedKotobaRouteImport; parentRoute: typeof AuthenticatedRouteRoute }
    '/_authenticated/listening': { id: '/_authenticated/listening'; path: '/listening'; fullPath: '/listening'; preLoaderRoute: typeof AuthenticatedListeningRouteImport; parentRoute: typeof AuthenticatedRouteRoute }
    '/_authenticated/profil': { id: '/_authenticated/profil'; path: '/profil'; fullPath: '/profil'; preLoaderRoute: typeof AuthenticatedProfilRouteImport; parentRoute: typeof AuthenticatedRouteRoute }
    '/_authenticated/progress': { id: '/_authenticated/progress'; path: '/progress'; fullPath: '/progress'; preLoaderRoute: typeof AuthenticatedProgressRouteImport; parentRoute: typeof AuthenticatedRouteRoute }
    '/_authenticated/quiz': { id: '/_authenticated/quiz'; path: '/quiz'; fullPath: '/quiz'; preLoaderRoute: typeof AuthenticatedQuizRouteImport; parentRoute: typeof AuthenticatedRouteRoute }
    '/_authenticated/quiz/$slug': { id: '/_authenticated/quiz/$slug'; path: '/quiz/$slug'; fullPath: '/quiz/$slug'; preLoaderRoute: typeof AuthenticatedQuizSlugRouteImport; parentRoute: typeof AuthenticatedRouteRoute }
    '/_authenticated/referral': { id: '/_authenticated/referral'; path: '/referral'; fullPath: '/referral'; preLoaderRoute: typeof AuthenticatedReferralRouteImport; parentRoute: typeof AuthenticatedRouteRoute }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBelajarRoute: typeof AuthenticatedBelajarRoute
  AuthenticatedBunpoRoute: typeof AuthenticatedBunpoRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDokkaiRoute: typeof AuthenticatedDokkaiRoute
  AuthenticatedDokkaiIdRoute: typeof AuthenticatedDokkaiIdRoute
  AuthenticatedKanjiRoute: typeof AuthenticatedKanjiRoute
  AuthenticatedKanjiIdRoute: typeof AuthenticatedKanjiIdRoute
  AuthenticatedKotobaRoute: typeof AuthenticatedKotobaRoute
  AuthenticatedListeningRoute: typeof AuthenticatedListeningRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedQuizRoute: typeof AuthenticatedQuizRoute
  AuthenticatedQuizSlugRoute: typeof AuthenticatedQuizSlugRoute
  AuthenticatedReferralRoute: typeof AuthenticatedReferralRoute
}
const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBelajarRoute,
  AuthenticatedBunpoRoute,
  AuthenticatedDashboardRoute,
  AuthenticatedDokkaiRoute,
  AuthenticatedDokkaiIdRoute,
  AuthenticatedKanjiRoute,
  AuthenticatedKanjiIdRoute,
  AuthenticatedKotobaRoute,
  AuthenticatedListeningRoute,
  AuthenticatedProfilRoute,
  AuthenticatedProgressRoute,
  AuthenticatedQuizRoute,
  AuthenticatedQuizSlugRoute,
  AuthenticatedReferralRoute,
}
const AuthenticatedRouteRouteWithChildren = AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute,
  ResetPasswordRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
