-- Applied to the ENO JAPAN Supabase project as migration:
-- v1_dokkai_reader_content_and_security_hardening
--
-- Includes:
-- 1. Restrict SECURITY DEFINER RPC execution to authenticated users.
-- 2. Add missing foreign-key indexes and remove duplicate question index.
-- 3. Upgrade one representative Dokkai passage per N5-N1 to long-form original reading with furigana and Indonesian translation.
-- 4. Add four comprehension questions per upgraded passage.
--
-- The production database was applied through Supabase migration tooling.
-- This repository file records the migration for source-control consistency.
