-- ENO JAPAN: persistent learning activity, leaderboard stats, and cached AI learning content
create table if not exists public.user_learning_stats (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  avatar_url text,
  jlpt_level text,
  ui_language text default 'id',
  xp integer not null default 0,
  total_points integer not null default 0,
  study_minutes integer not null default 0,
  lessons_completed integer not null default 0,
  quizzes_completed integer not null default 0,
  correct_answers integer not null default 0,
  total_answers integer not null default 0,
  current_streak integer not null default 0,
  longest_streak integer not null default 0,
  last_activity_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.learning_activity (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  activity_type text not null,
  content_type text,
  content_id text,
  points integer not null default 0,
  xp integer not null default 0,
  correct boolean,
  duration_seconds integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists learning_activity_user_created_idx on public.learning_activity(user_id, created_at desc);
create index if not exists user_learning_stats_leaderboard_idx on public.user_learning_stats(total_points desc, xp desc, last_activity_at asc);

create table if not exists public.ai_learning_content (
  id bigint generated by default as identity primary key,
  content_type text not null check (content_type in ('kotoba','bunpou')),
  content_id text not null,
  language text not null default 'id',
  examples jsonb not null default '[]'::jsonb,
  synonyms jsonb not null default '[]'::jsonb,
  antonyms jsonb not null default '[]'::jsonb,
  explanation text,
  model text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(content_type, content_id, language)
);

alter table public.user_learning_stats enable row level security;
alter table public.learning_activity enable row level security;
alter table public.ai_learning_content enable row level security;

-- Leaderboard stats must not be writable directly by users; activity is recorded through the function below.
create policy "users read own learning stats" on public.user_learning_stats for select using (auth.uid() = user_id);
create policy "users read own activity" on public.learning_activity for select using (auth.uid() = user_id);
create policy "users insert own activity" on public.learning_activity for insert with check (auth.uid() = user_id);
create policy "authenticated users read AI content" on public.ai_learning_content for select using (auth.role() = 'authenticated');

create or replace function public.record_learning_activity(
  p_activity_type text,
  p_content_type text default null,
  p_content_id text default null,
  p_points integer default 0,
  p_xp integer default 0,
  p_correct boolean default null,
  p_duration_seconds integer default 0,
  p_metadata jsonb default '{}'::jsonb
) returns public.user_learning_stats
language plpgsql security definer set search_path = public
as $$
declare
  r public.user_learning_stats;
  v_user uuid := auth.uid();
  v_points integer := greatest(coalesce(p_points,0),0);
  v_xp integer := greatest(coalesce(p_xp,0),0);
  v_seconds integer := greatest(coalesce(p_duration_seconds,0),0);
begin
  if v_user is null then raise exception 'Not authenticated'; end if;

  insert into public.learning_activity(user_id,activity_type,content_type,content_id,points,xp,correct,duration_seconds,metadata)
  values(v_user,p_activity_type,p_content_type,p_content_id,v_points,v_xp,p_correct,v_seconds,coalesce(p_metadata,'{}'::jsonb));

  insert into public.user_learning_stats(user_id,total_points,xp,study_minutes,lessons_completed,quizzes_completed,correct_answers,total_answers,last_activity_at,updated_at)
  values(v_user,v_points,v_xp,v_seconds/60,case when p_activity_type='lesson_completed' then 1 else 0 end,case when p_activity_type in ('quiz_completed','simulation_completed') then 1 else 0 end,case when p_correct=true then 1 else 0 end,case when p_correct is not null then 1 else 0 end,now(),now())
  on conflict(user_id) do update set
    total_points=public.user_learning_stats.total_points+v_points,
    xp=public.user_learning_stats.xp+v_xp,
    study_minutes=public.user_learning_stats.study_minutes+(v_seconds/60),
    lessons_completed=public.user_learning_stats.lessons_completed+case when p_activity_type='lesson_completed' then 1 else 0 end,
    quizzes_completed=public.user_learning_stats.quizzes_completed+case when p_activity_type in ('quiz_completed','simulation_completed') then 1 else 0 end,
    correct_answers=public.user_learning_stats.correct_answers+case when p_correct=true then 1 else 0 end,
    total_answers=public.user_learning_stats.total_answers+case when p_correct is not null then 1 else 0 end,
    last_activity_at=now(),
    updated_at=now();

  select * into r from public.user_learning_stats where user_id=v_user;
  return r;
end;
$$;

grant execute on function public.record_learning_activity(text,text,text,integer,integer,boolean,integer,jsonb) to authenticated;

create or replace view public.leaderboard as
select
  row_number() over(order by total_points desc, xp desc, last_activity_at asc nulls last) as rank,
  user_id, display_name, avatar_url, jlpt_level, total_points, xp,
  study_minutes, lessons_completed, quizzes_completed, correct_answers,
  total_answers, current_streak, longest_streak, last_activity_at
from public.user_learning_stats;
